[versions]
annotations = "24.0.1"

# plugins
dokka = "1.8.10"
kotlin = "1.8.10"
changelog = "2.1.2"
gradleIntelliJPlugin = "1.15.0"
qodana = "0.1.13"
kover = "0.6.1"

chapi = "2.1.2"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# chapi
chapi-domain = { group = "com.phodal.chapi", name = "chapi-domain", version.ref = "chapi" }
chapi-java = { group = "com.phodal.chapi", name = "chapi-ast-java", version.ref = "chapi" }
chapi-kotlin = { group = "com.phodal.chapi", name = "chapi-ast-kotlin", version.ref = "chapi" }
chapi-typescript = { group = "com.phodal.chapi", name = "chapi-ast-typescript", version.ref = "chapi" }

openai-gpt3 = "com.theokanning.openai-gpt3-java:service:0.14.0"

commonmark-core = "org.commonmark:commonmark:0.21.0"
commonmark-gfm-tables = "org.commonmark:commonmark-ext-gfm-tables:0.21.0"

github-api = "org.kohsuke:github-api:1.314"

kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0"

retrofit2-converter-jackson = "com.squareup.retrofit2:converter-jackson:2.9.0"
retrofit2-converter-gson = "com.squareup.retrofit2:converter-gson:2.9.0"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.14.2"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.14.2"

okhttp = "com.squareup.okhttp3:okhttp:4.4.1"
okhttp-sse = "com.squareup.okhttp3:okhttp-sse:4.4.1"

comate-spec-lang = "org.archguard.comate:spec-lang:0.2.0"
# will conflict with Intellij bundle
# json-path = "com.jayway.jsonpath:json-path:2.8.0"
json-pathkt = "com.nfeld.jsonpathkt:jsonpathkt:2.0.1"

# implementation("org.yaml:snakeyaml:2.2")
yaml = "org.yaml:snakeyaml:2.2"

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
openai = ["openai-gpt3", "retrofit2-converter-jackson", "retrofit2-converter-gson", "jackson-databind", "okhttp", "okhttp-sse"]
markdown = ["commonmark-core", "commonmark-gfm-tables"]
