[versions]
# libraries
annotations = "24.0.1"

# plugins
dokka = "1.8.10"
kotlin = "1.8.10"
changelog = "2.0.0"
gradleIntelliJPlugin = "1.13.3"
qodana = "0.1.13"
kover = "0.6.1"
ktor = "2.2.4"

chapi = "2.1.2"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
ktor-client-apache = { group = "io.ktor", name = "ktor-client-apache", version.ref = "ktor" }

# chapi
chapi-domain = { group = "com.phodal.chapi", name = "chapi-domain", version.ref = "chapi" }
chapi-java = { group = "com.phodal.chapi", name = "chapi-ast-java", version.ref = "chapi" }
chapi-kotlin = { group = "com.phodal.chapi", name = "chapi-ast-kotlin", version.ref = "chapi" }
chapi-typescript = { group = "com.phodal.chapi", name = "chapi-ast-typescript", version.ref = "chapi" }

# "com.theokanning.openai-gpt3-java:service:0.12.0"
openai-gpt3 = "com.theokanning.openai-gpt3-java:service:0.12.0"
retrofit2-converter-jackson = "com.squareup.retrofit2:converter-jackson:2.9.0"

commonmark-core = "org.commonmark:commonmark:0.21.0"
commonmark-gfm-tables = "org.commonmark:commonmark-ext-gfm-tables:0.21.0"

dotenv = "io.github.cdimascio:dotenv-kotlin:6.4.1"

# "org.kohsuke:github-api:1.314"
github-api = "org.kohsuke:github-api:1.314"

# org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0"

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
grammarKit = { id = "org.jetbrains.grammarkit", version = "2022.2.2" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
openai = ["openai-gpt3", "retrofit2-converter-jackson"]
markdown = ["commonmark-core", "commonmark-gfm-tables"]
